---
After:
  - framework/*
  - cms/*
---
StaticExporter:
  extensions:
    - DocumentationStaticPublisherExtension
  disable_sitetree_export: true
Controller:
  extensions:
    - ControllerExtension
UpdateTask:
  path: "/Sites/userhelp.silverstripe.org/assets"